development:
  adapter: mysql2
  encoding: utf8
  database: edushare_mobile_app_demo_development
  username: root
  password: root
  pool: 5
  timeout: 5000
  reconnect: true

test:
  adapter: mysql2
  encoding: utf8
  database: edushare_mobile_app_demo_test
  username: root
  password: root
  pool: 5
  timeout: 5000
  
production:
  adapter: mysql2
  encoding: utf8
  database: edushare_mobile_app_demo
  username: root
  password: root
  pool: 5
  timeout: 5000
  reconnect: true